### ISSUE TITLE
Add SASS compilation to deploy

### ISSUE THREAD

**Issue by iterational** [leukeleu/deploytool#14]
Compilation on server is suboptimal due to increased dependencies (Ruby). Compilation on git_pre_commit is suboptimal due to repo "polution".

If SASS was added to deploy:
- git would only have CSS
- only local system dependencies (no more git hooks though)
- compile on deploy

/discuss

(Chi Shang, Nick)

**Comment by ramonakira** [comment]
no longer using sass
