### ISSUE TITLE
Master broken due to out-of-date paramiko?

### ISSUE THREAD

**Issue by bartvanandel** [leukeleu/deploytool#42]
Last Friday I could not deploy using a fresh install of deploy-tool. The error message which appeared was pointing in a different direction ("ImportError: No module named Crypto"), but in the end it turns out that using a newer version of paramiko fixes the issue.

This did the trick (inside virtualenv):
```.shell
pip install paramiko==2
```

Probably using a more recent version than 2.0.0 will work, too, I didn't check.

**Comment by 153957** [comment]
The paramiko change log: http://www.paramiko.org/changelog.html#2.0.0

**Comment by bartvanandel** [comment]
Updating Fabric did the trick too. Fixed in commit 184cf55a1e56cd67116f9ed565248bc6400dc40e.
